# deploy:
# aws cloudformation deploy --template-file "cloudformation/ssm-param/string.cform.yaml" --stack-name "ssm-param-stack" --parameter-overrides ParamName="AdminEMailAddr" ParamValue="julio@daws25.org"

# get current value:
# aws ssm get-parameter --name "/env/project/AdminEMailAddr"

Description: CloudFormation template to create an SSM Parameter

Parameters:
  EnvId:
    Type: String
    Default: project

  ParamName:
    Type: String
    Description: Name of the SSM parameter

  ParamValue:
    Type: String
    Description: Value of the SSM parameter

Resources:
  SSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/env/${EnvId}/${ParamName}"
      Value: !Ref ParamValue
      Type: String

Outputs:
  SSMParameterName:
    Description: Name of the created SSM parameter
    Value: !Sub "/env/${EnvId}/${ParamName}"
